// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using System.Threading;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.Extensions.Logging;

#nullable enable

namespace Microsoft.EntityFrameworkCore.VistaDB.Internal
{
    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public static class VistaDBStrings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.EntityFrameworkCore.VistaDB.Properties.VistaDBStrings", typeof(VistaDBStrings).Assembly);

        /// <summary>
        ///     VistaDB does not support the 'AT TIME ZONE' SQL construct.
        /// </summary>
        public static string AtTimeZoneNotSupported
            => GetString("AtTimeZoneNotSupported");

        /// <summary>
        ///     VistaDB does not support Azure SQL options. Use 'UseVistaDB' instead.
        /// </summary>
        public static string AzureSqlOptionsNotSupported
            => GetString("AzureSqlOptionsNotSupported");

        /// <summary>
        ///     VistaDB does not support Azure Synapse options. Use 'UseVistaDB' instead.
        /// </summary>
        public static string AzureSynapseOptionsNotSupported
            => GetString("AzureSynapseOptionsNotSupported");

        /// <summary>
        ///     VistaDB does not support computed columns. Property '{property}' on entity '{entityType}' uses 'HasComputedColumnSql'.
        /// </summary>
        public static string ComputedColumnsNotSupported(object? property, object? entityType)
            => string.Format(
                GetString("ComputedColumnsNotSupported", nameof(property), nameof(entityType)),
                property, entityType);

        /// <summary>
        ///     The query would require a CTE ('WITH ... AS'), which VistaDB does not support. Try restructuring the query, or split it into multiple queries.
        /// </summary>
        public static string CteNotSupported
            => GetString("CteNotSupported");

        /// <summary>
        ///     VistaDB does not support 'DATEDIFF_BIG'. Use 'DATEDIFF' with a sufficiently small unit instead.
        /// </summary>
        public static string DateDiffBigNotSupported
            => GetString("DateDiffBigNotSupported");

        /// <summary>
        ///     VistaDB does not support 'DATEFROMPARTS' / 'DATETIMEFROMPARTS' SQL functions.
        /// </summary>
        public static string DateFromPartsNotSupported
            => GetString("DateFromPartsNotSupported");

        /// <summary>
        ///     VistaDB does not support extended properties (sp_addextendedproperty).
        /// </summary>
        public static string ExtendedPropertiesNotSupported
            => GetString("ExtendedPropertiesNotSupported");

        /// <summary>
        ///     VistaDB does not support full-text search (CONTAINS / FREETEXT).
        /// </summary>
        public static string FullTextSearchNotSupported
            => GetString("FullTextSearchNotSupported");

        /// <summary>
        ///     VistaDB does not support memory-optimized tables.
        /// </summary>
        public static string MemoryOptimizedTablesNotSupported
            => GetString("MemoryOptimizedTablesNotSupported");

        /// <summary>
        ///     VistaDB does not support the 'MERGE' statement.
        /// </summary>
        public static string MergeNotSupported
            => GetString("MergeNotSupported");

        /// <summary>
        ///     VistaDB does not support SQL window functions (e.g. 'ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ...)'). The query EF Core would emit uses one — typically because of a split-collection or paginated-collection translation. Restructure the query to avoid window functions, or split it into multiple round-trips.
        /// </summary>
        public static string WindowFunctionsNotSupported
            => GetString("WindowFunctionsNotSupported");

        /// <summary>
        ///     VistaDB does not support the SQL 'OUTPUT' clause.
        /// </summary>
        public static string OutputClauseNotSupported
            => GetString("OutputClauseNotSupported");

        /// <summary>
        ///     VistaDB does not support schemas. Entity type '{entityType}' is mapped to schema '{schema}'. Move it to the default schema (or omit 'HasDefaultSchema' / 'ToTable(..., schema)').
        /// </summary>
        public static string SchemasNotSupported(object? entityType, object? schema)
            => string.Format(
                GetString("SchemasNotSupported", nameof(entityType), nameof(schema)),
                entityType, schema);

        /// <summary>
        ///     VistaDB does not support sequences. Use IDENTITY columns instead.
        /// </summary>
        public static string SequencesNotSupported
            => GetString("SequencesNotSupported");

        /// <summary>
        ///     VistaDB does not support the 'sql_variant' data type.
        /// </summary>
        public static string SqlVariantNotSupported
            => GetString("SqlVariantNotSupported");

        /// <summary>
        ///     VistaDB does not support stored procedures.
        /// </summary>
        public static string StoredProceduresNotSupported
            => GetString("StoredProceduresNotSupported");

        /// <summary>
        ///     VistaDB does not support the SQL Server structural JSON type.
        /// </summary>
        public static string StructuralJsonNotSupported
            => GetString("StructuralJsonNotSupported");

        /// <summary>
        ///     VistaDB does not support temporal (system-versioned) tables. Entity type '{entityType}' is configured as temporal.
        /// </summary>
        public static string TemporalTablesNotSupported(object? entityType)
            => string.Format(
                GetString("TemporalTablesNotSupported", nameof(entityType)),
                entityType);

        /// <summary>
        ///     VistaDB does not support user-defined CLR types (UDTs).
        /// </summary>
        public static string UdtNotSupported
            => GetString("UdtNotSupported");

        /// <summary>
        ///     VistaDB does not support the SQL Server 'vector' data type.
        /// </summary>
        public static string VectorTypeNotSupported
            => GetString("VectorTypeNotSupported");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name)!;
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}
