// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Globalization;
using System.Text;

namespace Microsoft.EntityFrameworkCore.VistaDB.Update.Internal;

/// <summary>
///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
///     the same compatibility standards as public APIs. It may be changed or removed without notice in
///     any release. You should only use it directly in your code with extreme caution and knowing that
///     doing so can result in application failures when updating to a new Entity Framework Core release.
/// </summary>
public class VistaDBUpdateSqlGenerator : UpdateAndSelectSqlGenerator, IVistaDBUpdateSqlGenerator
{
    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public VistaDBUpdateSqlGenerator(UpdateSqlGeneratorDependencies dependencies)
        : base(dependencies)
    {
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         For the common case — INSERT into a table whose only read-back column is an auto-generated
    ///         IDENTITY PK — we emit <c>INSERT … ; SELECT scope_identity()</c> instead of the base
    ///         <c>INSERT … ; SELECT [Id] FROM [T] WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity()</c>.
    ///     </para>
    ///     <para>
    ///         <b>Why:</b> the base WHERE-clause approach is fragile in VistaDB during long multi-INSERT
    ///         batches (e.g., GraphUpdates spec-test fixture seed). The bisection probe (Plan §11)
    ///         confirmed that with the WHERE clause reduced to <c>[Id] = scope_identity()</c>, the
    ///         GraphUpdates seed still fails — meaning <c>scope_identity()</c> in the WHERE position
    ///         returns NULL or a stale value after several preceding INSERTs. The scalar projection
    ///         <c>SELECT scope_identity()</c> doesn't involve the WHERE clause's expression evaluation
    ///         path, so it should bypass whatever VistaDB engine quirk is in play. The
    ///         <c>ScopeIdentityProbeTest</c> in the FunctionalTests project already verifies the scalar
    ///         form returns the correct value.
    ///     </para>
    ///     <para>
    ///         For more complex inserts (computed columns, RowVersion, multiple read-backs) we still
    ///         fall through to the base <see cref="UpdateAndSelectSqlGenerator.AppendInsertAndSelectOperation" />
    ///         WHERE-clause-based path; those scenarios are not exercised by GraphUpdates and remain
    ///         covered by the original behavior.
    ///     </para>
    /// </remarks>
    public override ResultSetMapping AppendInsertOperation(
        StringBuilder commandStringBuilder,
        IReadOnlyModificationCommand command,
        int commandPosition,
        out bool requiresTransaction)
    {
        var operations = command.ColumnModifications;
        var readOperations = operations.Where(o => o.IsRead).ToList();

        // Fast-path: only read-back is an auto-generated INTEGER IDENTITY PK column. Emit scalar
        // SELECT scope_identity() instead of the WHERE-clause-based lookup.
        //
        // We must verify the column's ValueGenerationStrategy is IdentityColumn — otherwise this
        // path catches Guid keys generated by NEWSEQUENTIALID, bool keys with HasDefaultValue, etc.
        // where scope_identity() (which returns DECIMAL) is not the right read-back; VistaDB then
        // errors out trying to convert Decimal to Bit / UniqueIdentifier when EF Core consumes the
        // result. The strategy check is the same one VistaDBModificationCommandBatch.RequiresIdentityInsert
        // uses to decide whether to route through DDA.
        if (readOperations.Count == 1
            && readOperations[0] is { IsKey: true, UseCurrentValueParameter: false } idCol
            && idCol.Property is { } idProperty
            && idProperty.GetValueGenerationStrategy(
                   StoreObjectIdentifier.Table(command.TableName, command.Schema))
               == VistaDBValueGenerationStrategy.IdentityColumn)
        {
            var writeOperations = operations.Where(o => o.IsWrite).ToList();
            AppendInsertCommand(commandStringBuilder, command.TableName, command.Schema, writeOperations, readOperations: []);

            commandStringBuilder
                .Append("SELECT scope_identity()")
                .AppendLine(SqlGenerationHelper.StatementTerminator)
                .AppendLine();

            requiresTransaction = true;
            return ResultSetMapping.LastInResultSet;
        }

        return AppendInsertAndSelectOperation(commandStringBuilder, command, commandPosition, out requiresTransaction);

        // VistaDB: no analog — VistaDB does not support the OUTPUT clause, so we never take the
        // SqlServer OUTPUT-based path. Original SqlServer logic preserved for future revival.
        /*
            if (command.ColumnModifications.All(o => !o.IsRead) || CanUseOutputClause(command))
            {
                return AppendInsertReturningOperation(commandStringBuilder, command, commandPosition, out requiresTransaction);
            }

            var table = StoreObjectIdentifier.Table(command.TableName, command.Schema);

            return command.ColumnModifications.All(o =>
                !o.IsKey
                || !o.IsRead
                || o.Property?.GetValueGenerationStrategy(table) == SqlServerValueGenerationStrategy.IdentityColumn)
                ? AppendInsertAndSelectOperation(commandStringBuilder, command, commandPosition, out requiresTransaction)
                : AppendInsertSingleRowWithOutputInto(
                    commandStringBuilder,
                    command,
                    command.ColumnModifications.Where(o => o.IsKey).ToList(),
                    command.ColumnModifications.Where(o => o.IsRead).ToList(),
                    commandPosition,
                    out requiresTransaction);
        */
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public override ResultSetMapping AppendUpdateOperation(
            StringBuilder commandStringBuilder,
            IReadOnlyModificationCommand command,
            int commandPosition,
            out bool requiresTransaction)
        // VistaDB: no analog — no OUTPUT clause; always do UPDATE + SELECT @@ROWCOUNT.
        // Original SqlServer logic preserved below for future revival when VistaDB adds OUTPUT support.
        /*
            => CanUseOutputClause(command)
                ? AppendUpdateReturningOperation(commandStringBuilder, command, commandPosition, out requiresTransaction)
                : AppendUpdateAndSelectOperation(commandStringBuilder, command, commandPosition, out requiresTransaction);
        */
        => AppendUpdateAndSelectOperation(commandStringBuilder, command, commandPosition, out requiresTransaction);

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public override ResultSetMapping AppendDeleteOperation(
            StringBuilder commandStringBuilder,
            IReadOnlyModificationCommand command,
            int commandPosition,
            out bool requiresTransaction)
        // VistaDB: no analog — no OUTPUT clause; always do DELETE + SELECT @@ROWCOUNT.
        // Original SqlServer logic preserved below for future revival when VistaDB adds OUTPUT support.
        /*
            => CanUseOutputClause(command)
                ? AppendDeleteReturningOperation(commandStringBuilder, command, commandPosition, out requiresTransaction)
                : AppendDeleteAndSelectOperation(commandStringBuilder, command, commandPosition, out requiresTransaction);
        */
        => AppendDeleteAndSelectOperation(commandStringBuilder, command, commandPosition, out requiresTransaction);

    // VistaDB: no analog — SqlServer overrides AppendInsertCommand/AppendUpdateCommand/AppendDeleteCommand to
    // place an OUTPUT clause inside the statement, and AppendStoredProcedureCall to emit EXEC. VistaDB supports
    // neither OUTPUT nor stored procedures, so the base UpdateSqlGenerator implementation (plain INSERT/UPDATE/DELETE
    // followed by a separate SELECT) is correct. Original SqlServer surface preserved below for future revival.
    /*
        public virtual ResultSetMapping AppendBulkInsertOperation(
            StringBuilder commandStringBuilder,
            IReadOnlyList<IReadOnlyModificationCommand> modificationCommands,
            int commandPosition,
            out bool requiresTransaction)
        {
            // ...MERGE ... OUTPUT batching logic...
        }

        protected override void AppendInsertCommand(...) { AppendOutputClause(...) ... }
        protected override void AppendUpdateCommand(...) { AppendOutputClause(...) ... }
        protected override void AppendDeleteCommand(...) { AppendOutputClause(...) ... }

        public override ResultSetMapping AppendStoredProcedureCall(...) { commandStringBuilder.Append("EXEC "); ... }

        protected override void AppendReturningClause(StringBuilder, IReadOnlyList<IColumnModification>, string?)
            => AppendOutputClause(...);
    */

    /// <summary>
    ///     Determines whether the given column should participate in the SELECT-back's WHERE clause as
    ///     an IDENTITY-style lookup (<c>[col] = scope_identity()</c>) versus a parameter-based lookup
    ///     (<c>[col] = @p</c>).
    /// </summary>
    /// <remarks>
    ///     The base class returns <see langword="true" /> whenever the column is <c>IsKey + IsRead</c>,
    ///     which over-matches: a composite PK with an INT IDENTITY column AND a Guid column where both
    ///     are store-generated would have both columns marked <c>IsKey + IsRead</c>. The base WHERE
    ///     clause would emit <c>[IntKey] = scope_identity() AND [GuidKey] = scope_identity()</c>, and
    ///     VistaDB rejects the Decimal-to-UniqueIdentifier comparison with engine error 558
    ///     ("Invalid operand(s) data type for operator: ="). Restrict to columns whose property carries
    ///     the <see cref="VistaDBValueGenerationStrategy.IdentityColumn" /> strategy — the same check
    ///     used by <c>VistaDBModificationCommandBatch.RequiresIdentityInsert</c>.
    /// </remarks>
    protected override bool IsIdentityOperation(IColumnModification modification)
    {
        if (!base.IsIdentityOperation(modification))
        {
            return false;
        }

        if (modification.Property is { } property
            && property.DeclaringType.GetTableName() is { } tableName)
        {
            var storeObject = StoreObjectIdentifier.Table(tableName, property.DeclaringType.GetSchema());
            return property.GetValueGenerationStrategy(storeObject) == VistaDBValueGenerationStrategy.IdentityColumn;
        }

        return false;
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    protected override ResultSetMapping AppendSelectAffectedCountCommand(
        StringBuilder commandStringBuilder,
        string name,
        string? schema,
        int commandPosition)
    {
        commandStringBuilder
            .Append("SELECT @@ROWCOUNT")
            .AppendLine(SqlGenerationHelper.StatementTerminator)
            .AppendLine();

        return ResultSetMapping.LastInResultSet | ResultSetMapping.ResultSetWithRowsAffectedOnly;
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public override void AppendBatchHeader(StringBuilder commandStringBuilder)
    {
        // VistaDB: no analog — SqlServer emits `SET NOCOUNT ON` to suppress per-statement row-count
        // messages while keeping @@ROWCOUNT live. In VistaDB, NOCOUNT either is not supported or
        // it ALSO zeroes @@ROWCOUNT for subsequent statements, causing the SELECT @@ROWCOUNT used
        // by UpdateAndSelectSqlGenerator to always read 0 — which EF Core treats as a concurrency
        // violation (DbUpdateConcurrencyException "expected 1 row(s), but actually affected 0").
        // We omit the header entirely.
        // Original SqlServer logic preserved below for future revival when VistaDB grows an analog.
        /*
            commandStringBuilder
                .Append("SET NOCOUNT ON")
                .AppendLine(SqlGenerationHelper.StatementTerminator);
        */
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    public override void PrependEnsureAutocommit(StringBuilder commandStringBuilder)
    {
        // VistaDB: no analog — VistaDB has no IMPLICIT_TRANSACTIONS session setting; autocommit is always on.
        // Original SqlServer logic preserved below for future revival when VistaDB grows an analog.
        /*
            commandStringBuilder.Insert(0, $"SET IMPLICIT_TRANSACTIONS OFF{SqlGenerationHelper.StatementTerminator}{Environment.NewLine}");
        */
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    protected override void AppendIdentityWhereCondition(StringBuilder commandStringBuilder, IColumnModification columnModification)
    {
        SqlGenerationHelper.DelimitIdentifier(commandStringBuilder, columnModification.ColumnName);
        commandStringBuilder.Append(" = ");

        // When the caller supplied an explicit value for an IDENTITY column (the IDENTITY_INSERT path —
        // see VistaDBModificationCommandBatch.AddCommand), `scope_identity()` returns NULL because no
        // identity was generated. The SELECT-back's WHERE clause must then look up the row by the
        // explicit value parameter instead — otherwise EF Core sees 0 rows and throws
        // DbUpdateConcurrencyException. UseCurrentValueParameter is true exactly when the explicit value
        // was written into the INSERT.
        if (columnModification.UseCurrentValueParameter)
        {
            SqlGenerationHelper.GenerateParameterNamePlaceholder(commandStringBuilder, columnModification.ParameterName!);
        }
        else
        {
            commandStringBuilder.Append("scope_identity()");
        }
    }

    /// <summary>
    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
    ///     any release. You should only use it directly in your code with extreme caution and knowing that
    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
    /// </summary>
    protected override void AppendRowsAffectedWhereCondition(StringBuilder commandStringBuilder, int expectedRowsAffected)
        => commandStringBuilder
            .Append("@@ROWCOUNT = ")
            .Append(expectedRowsAffected.ToString(CultureInfo.InvariantCulture));
}
